# latest stable release of Rust
# BUILDER STAGE
FROM rust:1.96.0 AS builder

# switch our working directory to app
# app folder created for us
WORKDIR /app

# Install the required system depenedencies for our linking configuration 
RUN apt update && apt install lld clang -y
# copy all files from our working envireonment to our Docker image
COPY . .

# force sqlx to look for saved metadata instead of trying 
# to query a live data base
ENV SQLX_OFFLINE true

# EXPLAIN:
# OLD COMMAND 
# Build the binary from scratch. Takes long because you 
# have to build from scratch
# WARN: different to book script as he doesnt have any bin files
RUN cargo build --release --bin zero2prod

# RUNTIME STAGE
FROM rust:1.96.0-slim AS runtime

WORKDIR /app

# COPY compiled binary from the builder envireonment
# to our runtime envireonment
COPY --from=builder /app/target/release/zero2prod zero2prod

# We need to also copy our configuration
COPY configuration configuration

# add out production flag
ENV APP_ENVIRONMENT production

# docker run launches binary
ENTRYPOINT ["./zero2prod"]
