name: zero2prod
region: lon
features:
- buildpack-stack=ubuntu-22

jobs:
- name: migrate
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: false
    repo: 1workbasedstuff1/zero2prod
  source_dir: .
  kind: PRE_DEPLOY
  run_command: sqlx migrate run
  instance_size_slug: basic-xxs
  instance_count: 1
  envs:
  - key: APP_DATABASE__HOST
    scope: RUN_TIME
    value: "your-db-host.db.ondigitalocean.com"
  - key: APP_DATABASE__PORT
    scope: RUN_TIME
    value: "25060"
  - key: APP_DATABASE__USERNAME
    scope: RUN_TIME
    value: "doadmin"
  - key: APP_DATABASE__PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: "your-password"
  - key: APP_DATABASE__DATABASE_NAME
    scope: RUN_TIME
    value: "newsletter"
  - key: APP_DATABASE__REQUIRE_SSL
    scope: RUN_TIME
    value: "true"

ingress:
  rules:
  - component:
      name: zero2prod
    match:
      path:
        prefix: /

services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: 1workbasedstuff1/zero2prod
  health_check:
    http_path: /health_check
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: zero2prod
  source_dir: .
  envs:
  - key: APP_DATABASE__HOST
    scope: RUN_TIME
    value: "your-db-host.db.ondigitalocean.com"
  - key: APP_DATABASE__PORT
    scope: RUN_TIME
    value: "25060"
  - key: APP_DATABASE__USERNAME
    scope: RUN_TIME
    value: "doadmin"
  - key: APP_DATABASE__PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: "your-password"
  - key: APP_DATABASE__DATABASE_NAME
    scope: RUN_TIME
    value: "newsletter"
  - key: APP_DATABASE__REQUIRE_SSL
    scope: RUN_TIME
    value: "true"
